version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres_email
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"